Models/ErrorViewModel.cs
namespace Task.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ImportRequestResponseViewModel.cs
namespace Task.Models
{
    public class ImportRequestResponseViewModel
    {
        public int Id { get; set; }
        public string ImporterName { get; set; }
        public string ImporterEmail { get; set; }
        public string ImporterMobile { get; set; }
        public string ExportCountry { get; set; }
        public string ExportCity { get; set; }
        public DateTime ImportDate { get; set; }
        public List<ItemViewModel> ItemsList { get; set; }
    }
}

Models/ImportRequestViewModel.cs
namespace Task.Models
{
    public class ImportRequestViewModel
    {
        public string ImporterName { get; set; }
        public string ImporterEmail { get; set; }
        public string ImporterMobile { get; set; }
        public string ExportCountry { get; set; }
        public string ExportCity { get; set; }
        public DateTime ImportDate { get; set; }
    }
}

Models/ItemListRequestViewModel.cs
using System.ComponentModel.DataAnnotations;
using Task.Data.Entities;

namespace Task.Models
{
    public class ItemListRequestViewModel
    {
        public int ItemId { get; set; }
        public int RequestId { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemCount { get; set; }
    }
}

Models/ItemViewModel.cs
namespace Task.Models
{
    public class ItemViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public int Count { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Task.Models;

namespace Task.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ImportController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using Task.Data.Entities;
using Task.Models;
using Task.Services;

namespace Task.Controllers
{
    public class ImportController : Controller
    {
        private readonly ILogger<ImportController> _logger;
        private readonly IImportService _importService;

        public ImportController(ILogger<ImportController> logger, IImportService importService)
        {
            _logger = logger;
            _importService = importService;
        }

        public IActionResult Index()
        {
            var list = _importService.GetRequestList();
            return View(list);
        }

        public IActionResult CreateNewRequest()
        {
            var model = new ImportRequestResponseViewModel()
            {
                ItemsList=_importService.getItemsList(),
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult CreateNewRequest(ImportRequestResponseViewModel input)
        {
            var result = _importService.CreateRequest(input);
            return Json(result);
        }
        public IActionResult ViewRequest(int Id)
        {
            var model = _importService.GetRequestForView(Id);
            return View( model);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome in our import website </h1>
    <a href="/import">Create New Import Request</a>
</div>

Views/Import/CreateNewRequest.cshtml
@using Task.Models;
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ImportRequestResponseViewModel
<style>
    .tab-content {
        margin-top: 20px;
    }
</style>
<h1>Create New Import Request Wizard </h1>

    
<div class="container ">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="tab1-tab" data-bs-toggle="tab" data-bs-target="#tab1" type="button" role="tab" aria-controls="tab1" aria-selected="true">Importer Info</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="tab2-tab" data-bs-toggle="tab" data-bs-target="#tab2" type="button" role="tab" aria-controls="tab2" aria-selected="false">Select Items</button>
        </li>
        <li class="nav-item" role="presentation">
            <p class="nav-link" id="tab3-tab" data-bs-toggle="tab" data-bs-target="#tab3" type="button" role="tab" aria-controls="tab3" aria-selected="false">View request</p>
        </li>
    </ul>

    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="tab1" role="tabpanel" aria-labelledby="tab1-tab">
            <div class="row">
                <div class="mb-3 col-md-6">
                    <label for="ImporterName" class="form-label">Importer Name</label>
                    <input type="text" class="form-control input" id="ImporterName" placeholder="Importer Name" required>
                        <div class="valid-feedback">
                            Looks good!
                        </div>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="ImporterEmail" class="form-label">Importer Email</label>
                        <input type="email" class="form-control input" id="ImporterEmail" placeholder="Importer Email" required>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="ImporterMobile" class="form-label">Importer Mobile</label>
                        <input type="text" class="form-control input" id="ImporterMobile" placeholder="Importer Mobile" required>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="ExportCountry" class="form-label">Export Country</label>
                        <input type="text" class="form-control input" id="ExportCountry" placeholder="Export Country" required>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="ExportCity" class="form-label">Export City</label>
                        <input type="text" class="form-control input" id="ExportCity" placeholder="ExportCity" required>
                </div>
                <div class="mb-3 col-md-6">
                    <label for="ImportDate" class="form-label">Import Date</label>
                        <input type="date" class="form-control input" id="ImportDate" placeholder="Import Date" required>
                </div>
       
            </div>
            <button class="btn btn-primary float-end next-tab">Next</button>
        </div>
        <div class="tab-pane fade" id="tab2" role="tabpanel" aria-labelledby="tab2-tab">
            <div class="row">
                <div class="mb-3 col-md-6">
                    <label for="itemName" class="form-label"> Item</label>
                    <select class="form-control" id="itemName" >
                        <option value="">Select</option>
                        @foreach (var item in Model.ItemsList)
                        {
                            <option value="@item.Id">@item.Name</option>

                        }
                    </select>

                </div>
                <div class="mb-3 col-md-6">
                    <label for="ItemCount" class="form-label">Item Count</label>
                    <input type="number" min="0"value="1" class="form-control" id="ItemCount" >
                </div>
                <div class="mb-3 col-md-6">
                    <button class="btn btn-success" id="AddItem" placeholder="Import Date">Add Item </button>
                </div>

                <table id="ItemTable" class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Item Name</th>
                            <th scope="col">Count</th>
                            <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
            
               
                    </tbody>
                </table>
            </div>


            <button class="btn btn-secondary prev-tab">Previous</button>
            <button class="btn btn-primary float-end next-tab">Next</button>
        </div>
        <div class="tab-pane fade" id="tab3" role="tabpanel" aria-labelledby="tab3-tab">
      
                <div class="row">
                    <div class="mb-3 col-md-6">
                        <label for="ImporterNameText" class="form-label">Importer Name</label>
                        <p id="ImporterNameText">  </p>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="ImporterEmailText" class="form-label">Importer Email</label>
                        <p id="ImporterEmailText">  </p>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="ImporterMobileText" class="form-label">Importer Mobile</label>
                        <p id="ImporterMobileText">  </p>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="ExportCountry" class="form-label">Export Country</label>
                        <p id="ExportCountryText">  </p>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="ExportCityText" class="form-label">Export City</label>
                        <p id="ExportCityText">  </p>
                    </div>

                    <div class="mb-3 col-md-6">
                        <label for="ImportDate" class="form-label">Import Date</label>
                        <p id="ImportDateText">  </p>
                    </div>


                    <hr />

                    <table id="ItemTableView" class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Item Name</th>
                                <th scope="col">Count</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            <button class="btn btn-secondary prev-tab">Previous</button>
            <button id="SaveRequest"  class="btn btn-success float-end next-tab">Save Request</button>

        </div>
    </div>
</div>

Views/Import/Index.cshtml
@using ImportRequest = Task.Data.Entities.ImportRequest
@model List<ImportRequest>
@{
    ViewData["Title"] = "Import Requests";
}


<h1>@ViewData["Title"]</h1>


<button class="btn btn-secondary" onclick="location.href='@Url.Action("CreateNewRequest", "Import")'"> Create New</button>


<table class="table">
    <thead>
        <tr>
            <th>ImporterName </th>
            <th>ImporterEmail</th>
            <th>ImporterMobile </th>
            <th>ExportCountry </th>
            <th>ExportCity  </th>
            <th>ImportDate   </th>
            <th>View   </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var request in Model)
        {
            <tr>
                <td>@request.ImporterName</td>
                <td>@request.ImporterEmail</td>
                <td>@request.ImporterMobile</td>
                <td>@request.ExportCountry</td>
                <td>@request.ExportCity</td>
                <td>@request.ImportDate.ToString("yyyy-MM-dd ")</td>
                <td><button class="btn btn-secondary Viewrequest" data-id="@request.Id"> View</button></td>
            </tr>
        }
    </tbody>
</table>
<div class="modal fade" id="ShowRequestDetail" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalToggleLabel">View Request Detail</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="RequestDetail">



            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">Close</button>
            </div>
        </div>
    </div>
</div>

Views/Import/ViewRequest.cshtml
@using Task.Models;
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model ImportRequestResponseViewModel

@{
    Layout = null;
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link href="~/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/css/bootstrap.rtl.css" rel="stylesheet" />
<link href="~/css/bootstrap.rtl.min.css" rel="stylesheet" />
<link href="~/css/bootstrap.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> 
<div class="container">

    <div class="row">
        <div class="mb-3 col-md-6">
            <label for="ImporterNameText" class="form-label">Importer Name</label>
            <p id="ImporterNameText"> @Model.ImporterName </p>
        </div>

        <div class="mb-3 col-md-6">
            <label for="ImporterEmailText" class="form-label">Importer Email</label>
            <p id="ImporterEmailText"> @Model.ImporterEmail  </p>
        </div>

        <div class="mb-3 col-md-6">
            <label for="ImporterMobileText" class="form-label">Importer Mobile</label>
            <p id="ImporterMobileText">  @Model.ImporterMobile </p>
        </div>

        <div class="mb-3 col-md-6">
            <label for="ExportCountryText" class="form-label">Export Country</label>
            <p id="ExportCountryText">   @Model.ExportCountry</p>
        </div>

        <div class="mb-3 col-md-6">
            <label for="ExportCityText" class="form-label">Export City</label>
            <p id="ExportCityText"> @Model.ExportCity  </p>
        </div>

        <div class="mb-3 col-md-6">
            <label for="ImportDateText" class="form-label">Import Date</label>
            <p id="ImportDateText"> @Model.ImportDate.ToString("yyyy-MM-dd ")  </p>
        </div>
         

        <table id="ItemTableView" class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Item Name</th>
                    <th scope="col">Count</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ItemsList)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Count
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Task.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="import" asp-action="index">Import Requests</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.esm.js"></script>
    <script src="~/js/bootstrap.esm.min.js"></script>
    <script src="~/js/bootstrap.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/js/customscript.js"></script>

</body>
</html>